"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockV3Aggregator__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MockV3Aggregator__factory_1 = require("./MockV3Aggregator__factory");
Object.defineProperty(exports, "MockV3Aggregator__factory", { enumerable: true, get: function () { return MockV3Aggregator__factory_1.MockV3Aggregator__factory; } });
