"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FundMe__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var FundMe__factory_1 = require("./FundMe__factory");
Object.defineProperty(exports, "FundMe__factory", { enumerable: true, get: function () { return FundMe__factory_1.FundMe__factory; } });
